# Generated by Django 2.0.6 on 2020-10-07 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userreq',
            fields=[
                ('Donor_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contact', models.IntegerField(max_length=10)),
                ('Age', models.IntegerField(default='')),
                ('Blood_group', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=10)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
